name: Eczane Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir çalışır
  workflow_dispatch:  

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
        
    - name: Run bot
      run: node eczane.js
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add eczaneler.json
        git commit -m "Update eczane data" || exit 0
        git push
