name: Eczane Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir çalışır
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install blinker
        
    - name: Run bot
      run: |
        chromedriver --version
        google-chrome --version
        python app.py
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add eczaneler.json debug_*.json
        git commit -m "Update eczane data" || exit 0
        git push


